# Generated by Django 3.0 on 2019-12-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tecnologias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tecnologias',
            new_name='Tecnologia',
        ),
        migrations.AlterModelOptions(
            name='tecnologia',
            options={'verbose_name': 'Tecnologia', 'verbose_name_plural': 'Tecnologias'},
        ),
    ]
